name: solidstore

# Next.js v16 docs doesn't recommend using compose for development.
services:
  postgres-dev:
    container_name: solidstore-db-dev
    build:
      dockerfile: Dockerfile
      context: db
    volumes:
      # Persists records
      - ./db/docker/data:/var/lib/postgresql/18/docker
    ports:
      - 5432:5432
    networks:
      solidstore-network-dev:
        ipv4_address: 192.168.12.4

  caddy-dev:
    extra_hosts:
    - "host.docker.internal:host-gateway"
    container_name: solidstore-caddy-dev
    build:
      dockerfile: Dockerfile
      context: caddy
    volumes:
      - ./caddy/dev:/etc/caddy
      - ./caddy/dev/data:/data
      - ./caddy/dev/config:/config
    ports:
      - 5213:5213
      - 5313:5313
    networks:
      solidstore-network-dev:
        ipv4_address: 192.168.12.5

networks:
  solidstore-network-dev:
    name: solidstore-network-dev
    enable_ipv6: false
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
          ip_range: 192.168.12.0/24
          gateway: 192.168.12.1
