# If you're a localstack pro user, you can opt-in for persistence by
# 1. setting up your credentials in the localstack conservicetainer below
# 2. uncomment the "volumes" sequence in postgres-dev service below

name: solidstore

# Next.js v16 docs doesn't recommend using compose for development.
services:
  postgres-dev:
    container_name: solidstore-db-dev
    build:
      dockerfile: Dockerfile
      context: db
    # Doesn't persist records. Use this if have localstack doesn't persist data
    volumes:
      - /var/lib/postgresql/18/docker
    # Persists records. You can use this if localstack persists data
    # volumes:
    #   - ./db/docker/data:/var/lib/postgresql/18/docker
    ports:
      - 5432:5432
    networks:
      solidstore-network-dev:
        ipv4_address: 192.168.0.4

  caddy-dev:
    container_name: solidstore-caddy-dev
    build:
      dockerfile: Dockerfile
      context: caddy
    volumes:
      - ./caddy/dev:/etc/caddy
      - ./caddy/dev/data:/data
      - ./caddy/dev/config:/config
    ports:
      - 5213:5213
      - 5313:5313
    networks:
      solidstore-network-dev:
        ipv4_address: 192.168.0.5

  localstack-dev:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    # If you need persistence, you need a pro version and use theh localstack-pro image
    image: localstack/localstack:4.10.0
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      # If you need persistence, you need a pro version and set your auth token with LOCALSTACK_AUTH_TOKEN
      - DEBUG=${DEBUG:-1}
      - PERSISTENCE=${PERSISTENCE:-1}
      - SNAPSHOT_SAVE_STRATEGY=ON_SHUTDOWN
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=https://localhost.localstack.cloud:4566
    volumes:
      # Persist data. You don't need to but you can remove this line if you don't have localstack pro
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-vol}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-setup.sh:/etc/localstack/init/ready.d/localstack-setup.sh"
    healthcheck:
      test: ["CMD-SHELL", "awslocal s3 ls"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  solidstore-network-dev:
    name: solidstore-network-dev
    enable_ipv6: false
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          ip_range: 192.168.0.0/24
          gateway: 192.168.0.1
